app/dataStorage/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
app_name = 'dataStorage'
urlpatterns = [
	#path('/', login_required(iViews.familyList.as_view()), name='familyList'),
	path('', views.home, name='home'),
]

app/main/urls.py
from django.contrib import admin
from django.urls import path
from . import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('dataStorage.urls')),
	path('accounts/',include('registration.backends.simple.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT,)

app/dataStorage/models.py
from django.db import models

# Create your models here.

app/dataStorage/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse, get_resolver
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.signals import user_logged_out, user_logged_in, user_login_failed
from django.dispatch import receiver

@receiver(user_logged_out)
def on_user_logged_out(sender, request, **kwargs):
	messages.info(request, '['+request.user.username+'] Logged out.')

@receiver(user_logged_in)
def on_user_logged_in(sender, request, **kwargs):
	messages.success(request, '['+request.user.username+'] Logged in.')

@receiver(user_login_failed)
def on_user_login_failed(sender, request, **kwargs):
	messages.warning(request, 'Logged in failed.')

@login_required
def home(request):
	context = {}
	#messages.info(request, 'Information')
	#messages.success(request, 'Successful')
	#messages.warning(request, 'Warning')
	return render(request, 'home.html', context)

app/templates/base.html
<!doctype html>
<html>
	<head>{% load static %}
		{% block stylesheet %}{% endblock stylesheet %}
		<link rel="stylesheet" href="{% static 'css/navbar-static-top.css' %}">
		<link rel="stylesheet" href="{% static 'css/navbar-top.css' %}">
		<link rel="stylesheet" href='{% static "css/bootstrap.css" %}' type="text/css"/>
		<link rel="stylesheet" href='{% static "css/bootstrap-icons.css" %}' type="text/css"/>
		<link rel="stylesheet" href='{% static "css/all.css" %}' type="text/css"/>
		<link rel="stylesheet" href='{% static "css/animate.css" %}' type="text/css"/>
		<link rel="shortcut icon" href="{% static 'images/favicon.ico' type='image/x-icon' %}">
		<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
			::-webkit-scrollbar {
				width: 1px;
			}

			[data-notify="progressbar"]
			{
				margin-bottom: 0px;
				position: absolute;
				bottom: 0px;
				left: 0px;
				width: 100%;
				height: 5px;
			}
    </style>
		{% block javascript %}{% endblock javascript %}
		<script type="text/javascript" src='{% static "javascript/jquery.js" %}'></script>
    <script type="text/javascript" src='{% static "javascript/bootstrap.js" %}'></script>
    <script type="text/javascript" src='{% static "javascript/bootstrap-notify.js" %}'></script>
		{% if messages %}
		<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
		  <symbol id="success" fill="currentColor" viewBox="0 0 16 16">
		    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
		  </symbol>
		  <symbol id="primary" fill="currentColor" viewBox="0 0 16 16">
		    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
		  </symbol>
		  <symbol id="info" fill="currentColor" viewBox="0 0 16 16">
		    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
		  </symbol>
		  <symbol id="warning" fill="currentColor" viewBox="0 0 16 16">
		    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
		  </symbol>
		</svg>
		<script>
			$(document).ready(function() {
				{% for message in messages %}
					$.notify('{{ message }}',
						{
							type: '{{ message.tags }}',
							showProgressbar: true,
							placement: {
								from: "top",
								align: "center"
							},
							delay: 5000,
							animate: {
								enter: "animate__animated animate__flipInX",
								exit: "animate__animated animate__fadeOutUp"
							},
						});
				{% endfor %}
			});
		</script>
		{% endif %}
		<title>{% block title %}eSpace{% endblock title %}</title>
	</head>
	<body class="text-white bg-dark" id="bgTag" {% block bodyTag %}{% endblock bodyTag %}>
		{% block javascriptEnd %}{% endblock javascriptEnd %}
		{% include 'navbar.html' %}
    <main role="main" class="container">
			{% block content %}{% endblock content %}
		</main>
		<script type="text/javascript">
      const btn = document.querySelector('#darkMode')
      const bg = document.querySelector('#bgTag')
      btn.onclick = () => {
          darkModeOn = bg.classList.contains("bg-dark")
          if(darkModeOn === true){
						btn.classList.remove("bi-lightbulb-off")
						btn.classList.add("bi-lightbulb")
            bg.classList.remove("bg-dark")
            bg.classList.remove("text-white")
          }else if(darkModeOn === false){
						btn.classList.remove("bi-lightbulb")
						btn.classList.add("bi-lightbulb-off")
            bg.classList.add("bg-dark")
            bg.classList.add("text-white")
          }
      }
    </script>
	</body>
</html>

app/templates/baseFull.html
<!doctype html>
<html lang="en">
  <head>{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block stylesheet %}{% endblock stylesheet %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.css" integrity="sha384-WMgof6iSOcGGUSSHbZXThOpcZmVDpwSrc/X0L5IpeicPQn/qAkFwm5uwZZKx0SCS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" integrity="sha384-tKLJeE1ALTUwtXlaGjJYM3sejfssWdAaWR2s97axw4xkiAdMzQjtOjgcyw0Y50KU" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    {% if messages %}
		<script>
			$(document).ready(function() {
				{% for message in messages %}
					$.notify('{{ message }}',
						{
							type: '{{ message.tags }}',
							placement: {
								from: "top",
								align: "center"
							},
							delay: 5000,
							animate: {
								enter: "animate__animated animate__flipInX",
								exit: "animate__animated animate__fadeOutUp"
							},
						});
				{% endfor %}
			});
		</script>
		{% endif %}
    <title>{% block title %}eSpace{% endblock title %}</title>
  </head>
  <body class="text-white bg-dark" id="bgTag"><!-- class="dark-mode"-->
    <main role="main" class="container">
			{% block content %}{% endblock content %}
		</main>
    <i class="bi bi-house-fill"></i>
    <div class="form-check form-switch">
      <input class="form-check-input" type="checkbox" id="darkMode" checked>
      <label class="form-check-label" for="darkMode">Dark mode</label>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.js" integrity="sha384-zlQmapo6noJSGz1A/oxylOFtN0k8EiXX45sOWv3x9f/RGYG0ECMxTbMao6+OLt2e" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.js" integrity="sha384-/DJx+Iu1blm34FpB0PqizFYVgJGpOh8hl3OWJLEKiqVMsLSW9cNjs9Y566t96ekj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.js" integrity="sha384-TwXPs96wsaE/FmWpxAx89Bmk0+jyVtezHCrozWgrsjzx2sxfoCy8DisIMEvoK1AG" crossorigin="anonymous"></script>
    -->
    <script type="text/javascript">
      const btn = document.querySelector('#darkMode')
      const bg = document.querySelector('#bgTag')
      btn.onclick = () => {
          darkModeOn = bg.classList.contains("bg-dark")
          if(darkModeOn === true){
            bg.classList.remove("bg-dark")
            bg.classList.remove("text-white")
          }else if(darkModeOn === false){
            bg.classList.add("bg-dark")
            bg.classList.add("text-white")
          }
      }
    </script>
  </body>
</html>

app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome, {{ request.user.username }}</h1>
<div class="alert alert-primary d-flex align-items-center alert-dismissible fade show" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
    <use xlink:href="#primary"/></svg>
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<div class="alert alert-info d-flex align-items-center alert-dismissible fade show" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
    <use xlink:href="#primary"/></svg>
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
    <use xlink:href="#success"/></svg>
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<div class="alert alert-warning d-flex align-items-center alert-dismissible fade show" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
    <use xlink:href="#warning"/></svg>
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
    <use xlink:href="#warning"/></svg>
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endblock content %}

app/templates/home[old].html
{% extends 'base.html' %}
{% block stylesheet %}
  {% load webpush_notifications %}
  {% webpush_header %}
{% endblock stylesheet %}

{% block content %}
<h1>Welcome, {{ request.user.username }}</h1>
{% webpush_button with_class="btn btn-outline-info" %}
{% endblock content %}

app/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div id="navbarCollapse" class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item active">
          <a class="nav-link active" href="{% url 'dataStorage:home' %}"><i class="bi bi-house-fill"></i> Home </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://github.com/rshnGhost/eSpace"><i class="bi bi-github"></i> Get This Code</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#contact"><i class="bi bi-telephone-fill"></i> Contact</a>
        </li>
        <li class="nav-item">
          <div class="nav-link py-1"><i class="btn btn-dark py-1 bi bi-lightbulb-off" id="darkMode"></i></div>
        </li>
        </ul>
        <ul class="navbar-nav">
        <li class="nav-item">
        {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
        <form class="d-flex" action="{% url 'auth_login' %}" method="post">
          {% csrf_token %}
            <input type="text" class="form-control me-2" name="username" placeholder="Username">
            <input type="password" class="form-control me-2" name="password" placeholder="Password">
            <input type="submit" class="btn btn-outline-success my-2 my-sm-0" value="Login">
        </form>
        {% endif %}
        </li>
        {% if request.user.is_authenticated and user %}
        <li class="nav-item active">
          <a {% if request.user.is_staff %}href="{% url 'admin:index' %}"{% endif %} class="nav-link">{{ user }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auth_logout' %}"><i class="bi bi-box-arrow-right"></i> Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration_register' %}"><i class="bi bi-person-plus-fill"></i> Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
</nav>